<template>
  <footer v-show="isCvVisible" class="footer has-text-centered">
    <p>
      Made with <span class="is-inline-flex heartbeat">♥︎</span> by
      {{ fullName }}
    </p>
    <p class="heading mb-0">Thanks for taking the time!</p>
  </footer>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { useProfileStore, useGlobalState, store } from '@stores';

export default defineComponent({
  name: 'OFooter',
  setup() {
    const { fullName } = useProfileStore(store);
    const { isCvVisible } = useGlobalState();

    return { fullName, isCvVisible };
  },
});
</script>

<style scoped>
.heartbeat {
  animation: heartbeat 1.5s ease-in-out infinite both;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-9-20 17:1:18
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@keyframes heartbeat {
  from {
    transform: scale(1);
    transform-origin: center center;
    animation-timing-function: ease-out;
  }
  10% {
    transform: scale(0.91);
    animation-timing-function: ease-in;
  }
  17% {
    transform: scale(0.98);
    animation-timing-function: ease-out;
  }
  33% {
    transform: scale(0.87);
    animation-timing-function: ease-in;
  }
  45% {
    transform: scale(1);
    animation-timing-function: ease-out;
  }
}
</style>
